[package]
name = "rust_chess"
version = "0.2.0"
authors = ["Lev <lev.kokotov@gmail.com>"]

[dependencies]
colored = "1.6"
regex = "0.2"
lazy_static = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
cgmath = "*"
gl = "0.9.0"
glfw = "0.24.0"
tobj = "*"
reqwest = "*"
